### PR TITLE
REST tests: remember to clean up test request context

### PR DESCRIPTION
**Pull request by tehasdf**
We can't just push and push, gotta pop sometimes too :)

Otherwise, the request context sticks around, and in each next
request, we still have the same current_user.

This seemed to work fine in 3.6, but started erroring out in 3.10,
I'm not entirely sure why

### CODE REVIEW

**Review by glukhman — APPROVED** [review]

File: rest-service/manager_rest/test/base_test.py [hunk 1]
```diff
@@ -303,6 +303,10 @@ def setUpClass(cls):
         cls.client = cls.create_client()
 
     def setUp(self):
+        test_context = server.app.test_request_context()
+        test_context.push()  # type: ignore
```
Comment (geokala) [inline rest-service/manager_rest/test/base_test.py:307]: What makes us need ti not check type here?

Comment (tehasdf) [reply rest-service/manager_rest/test/base_test.py:307]: hmm:
```
manager_rest/test/base_test.py:307: error: "ContextManager[RequestContext]" has no attribute "push"
manager_rest/test/base_test.py:308: error: "ContextManager[RequestContext]" has no attribute "pop"
``` I'm not sure why. It does have those.

Comment (tehasdf) [reply rest-service/manager_rest/test/base_test.py:307]: Ah, flask 2.x fixes this
